#Target : Dependencies

#<TAB>commands



Build : maincode.c functions.c

    gcc maincode.c functions.c -o maincode.out



Run : Build

    ./maincode.out



Clean:

    rm -rf *.o *.out *.s *.i *.txt