#Target : Dependencies

#<TAB>commands



Build : maincode.c functions.c unity.c 

    gcc maincode.c functions.c unity.c -o output.out



Run : Build

    ./output.out



Clean:

    rm -rf *.o *.out *.s *.i 